# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PreedictLabel = QtWidgets.QLabel(self.centralwidget)
        self.PreedictLabel.setObjectName("PreedictLabel")
        self.gridLayout.addWidget(self.PreedictLabel, 5, 1, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 5)
        self.PeopleNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.PeopleNumber.setObjectName("PeopleNumber")
        self.gridLayout.addWidget(self.PeopleNumber, 6, 3, 1, 1)
        self.PredictIMGView = QtWidgets.QGraphicsView(self.centralwidget)
        self.PredictIMGView.setObjectName("PredictIMGView")
        self.gridLayout.addWidget(self.PredictIMGView, 6, 0, 1, 3)
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout.addWidget(self.NextButton, 7, 2, 1, 1)
        self.tableHistory = QtWidgets.QTableWidget(self.centralwidget)
        self.tableHistory.setObjectName("tableHistory")
        self.tableHistory.setColumnCount(0)
        self.tableHistory.setRowCount(0)
        self.gridLayout.addWidget(self.tableHistory, 6, 5, 1, 1)
        self.GraphView = QtWidgets.QGraphicsView(self.centralwidget)
        self.GraphView.setObjectName("GraphView")
        self.gridLayout.addWidget(self.GraphView, 6, 4, 1, 1)
        self.PreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousButton.setObjectName("PreviousButton")
        self.gridLayout.addWidget(self.PreviousButton, 7, 0, 1, 1)
        self.GraphLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphLabel.setObjectName("GraphLabel")
        self.gridLayout.addWidget(self.GraphLabel, 5, 4, 1, 1)
        self.Model_Select = QtWidgets.QComboBox(self.centralwidget)
        self.Model_Select.setObjectName("Model_Select")
        self.Model_Select.addItem("")
        self.Model_Select.addItem("")
        self.Model_Select.addItem("")
        self.Model_Select.addItem("")
        self.Model_Select.addItem("")
        self.gridLayout.addWidget(self.Model_Select, 0, 5, 2, 1)
        self.HistoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.HistoryLabel.setObjectName("HistoryLabel")
        self.gridLayout.addWidget(self.HistoryLabel, 5, 5, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PreedictLabel.setText(_translate("MainWindow", "Predict IMG"))
        self.NextButton.setText(_translate("MainWindow", "Next"))
        self.PreviousButton.setText(_translate("MainWindow", "Previous"))
        self.GraphLabel.setText(_translate("MainWindow", "Graph"))
        self.Model_Select.setItemText(0, _translate("MainWindow", "YoloV5"))
        self.Model_Select.setItemText(1, _translate("MainWindow", "YOloV8"))
        self.Model_Select.setItemText(2, _translate("MainWindow", "Mask-R-CNN"))
        self.Model_Select.setItemText(3, _translate("MainWindow", "Faster-R-CNN"))
        self.Model_Select.setItemText(4, _translate("MainWindow", "CSRNet"))
        self.HistoryLabel.setText(_translate("MainWindow", "History"))
